services:
  app:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8888:8000"
    restart: on-failure
    depends_on:
      - pg
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  pg:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_NAME:-db}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db:/var/lib/postgresql/data

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"    # MinIO API
      - "9001:9001"    # MinIO console
    volumes:
      - ./minio/data:/data                  # MinIO data storage
      - ./minio/config:/root/.minio         # MinIO configuration
    command: server /data --console-address ":9001"



#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"
