# Generated by Django 5.1.7 on 2025-04-04 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="age",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100, message="Invalid age")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Invalid email address"
                    )
                ],
            ),
        ),
    ]
