# Generated by Django 5.1.7 on 2025-03-20 11:54

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profilemodel_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="age",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="test-bucket"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="surname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
